In [1]:
%load_ext autoreload
%autoreload 2

In [11]:
from regression import *
import pathlib
from sklearn.preprocessing import StandardScaler
import numpy as np

TypeError: LogisticRegressor.sigmoid() missing 1 required positional argument: 'z'

In [6]:
X_train, X_val, y_train, y_val = utils.loadDataset(
        features=[
            'Penicillin V Potassium 500 MG',
            'Computed tomography of chest and abdomen',
            'Plain chest X-ray (procedure)',
            'Low Density Lipoprotein Cholesterol',
            'Creatinine',
            'AGE_DIAGNOSIS'
        ],
        split_percent=0.8,
        split_seed=42
    )

    # Scale the data, since values vary across feature. Note that we
    # fit on the training data and use the same scaler for X_val.
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)

In [20]:
LogisticRegressor.sigmoid(np.dot(X_train, W))

array([0.71142906, 0.33110202, 0.10039875, ..., 0.15243358, 0.92437913,
       0.67574119])

In [12]:
num_feats=6
W = np.random.randn(num_feats + 1).flatten()

In [100]:
X_train, X_val, y_train, y_val = utils.loadDataset(
features=[
			'Penicillin V Potassium 500 MG',
			'Computed tomography of chest and abdomen',
			'Plain chest X-ray (procedure)',
			'Low Density Lipoprotein Cholesterol',
			'Creatinine',
			'AGE_DIAGNOSIS'
		],
		split_percent=0.8,
		split_seed=42
)

np.random.seed(0)
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_val = sc.transform(X_val)

	# For testing purposes, once you've added your code.
	# CAUTION: hyperparameters have not been optimized.
num_feats = 6
log_model = logreg.LogisticRegressor(num_feats=6, learning_rate=0.00001, tol=0.01, max_iter=10, batch_size=10)
log_model.W = np.zeros(num_feats + 1).flatten()
log_model.train_model(X_train, y_train, X_val, y_val)


In [102]:
np.isclose(val_loss,0.003431961882810284)



True

In [86]:
log_model.make_prediction(X_val)

ValueError: shapes (400,8) and (7,) not aligned: 8 (dim 1) != 7 (dim 0)

In [51]:
val_loss = log_model.loss_function(y_val, log_model.make_prediction(X_val))

In [52]:
val_loss

0.003431961882810284

In [79]:
grad

array([-0.33097326, -0.42723908, -0.48789866, -0.        , -0.        ,
        0.11667581,  0.04846649])

In [61]:
log_model.W

array([-0.98300084,  0.56123626,  1.23872425, -0.13016886,  1.65527511,
       -0.52718774, -0.65783616])

In [64]:
(y_train)

array([1., 1., 0., ..., 0., 1., 0.])

In [71]:
log_model.loss_hist_val[0:10]

[0.0034659997110664973,
 0.0034647765626905623,
 0.0034650843770131835,
 0.003464409889815148,
 0.0034641219055323593,
 0.0034638325084951336,
 0.0034629164314393997,
 0.003461666284869979,
 0.0034604332792806326,
 0.0034602473029646517]

In [76]:
grad

array([-0.48704934, -0.2529591 , -0.3267267 , -0.        , -0.        ,
        0.1070174 , -0.05264797])